import type { Hotspot, ConflictZone, MilitaryBase, UnderseaCable, NuclearFacility, StrategicWaterway, APTGroup, EconomicCenter, Spaceport, CriticalMineralProject } from '@/types';
import { MILITARY_BASES_EXPANDED } from './bases-expanded';

// JapanMonitor: Hotspots focused on Japan and regional security concerns
// Hotspot levels are NOT hardcoded - they are dynamically calculated based on news activity
// All hotspots start at 'low' and rise to 'elevated' or 'high' based on matching news items
// Escalation scores: 1=stable, 2=watchlist, 3=elevated, 4=high tension, 5=critical/active conflict
export const INTEL_HOTSPOTS: Hotspot[] = [
  {
    id: 'tokyo',
    name: 'Tokyo',
    subtext: 'Capital/Government',
    lat: 35.6762,
    lon: 139.6503,
    location: 'Tokyo, Japan',
    keywords: ['tokyo', 'japan', 'japanese', 'kishida', 'ldp', 'diet', 'kantei', 'kasumigaseki', 'prime minister', 'japan government', 'tokyo stock exchange', 'bank of japan', 'boj', 'nikkei', 'yen'],
    agencies: ['Japanese Government', 'Bank of Japan', 'MOD', 'MOFA'],
    description: 'Japanese capital, government center, and major financial hub. Political and economic heart of Japan.',
    status: 'Monitoring',
    escalationScore: 1,
    escalationTrend: 'stable',
    escalationIndicators: ['Stable democracy', 'Strong US alliance', 'Regional security cooperation'],
    history: {
      lastMajorEvent: 'Kishida leadership',
      lastMajorEventDate: '2021-10-04',
      precedentCount: 0,
      precedentDescription: 'Post-war democratic stability since 1945',
      cyclicalRisk: 'Earthquake/tsunami vulnerability',
    },
    whyItMatters: "World's 3rd largest economy; G7 member; US-Japan Security Treaty anchor; regional stability leader",
  },
  {
    id: 'okinawa',
    name: 'Okinawa',
    subtext: 'US Military Hub',
    lat: 26.2124,
    lon: 127.6809,
    location: 'Okinawa Prefecture, Japan',
    keywords: ['okinawa', 'futenma', 'kadena', 'camp foster', 'us marines', 'us military', 'base relocation', 'henoko', 'ospreys', 'japan defense'],
    agencies: ['USFJ', 'JSDF', 'III MEF', '18th Wing'],
    description: 'Major US military presence in Asia-Pacific. Strategic location for regional security operations.',
    status: 'Monitoring',
    escalationScore: 2,
    escalationTrend: 'stable',
    escalationIndicators: ['US force presence 30K+', 'Base relocation tensions', 'Regional deterrence posture'],
    history: {
      lastMajorEvent: 'Futenma relocation debate',
      lastMajorEventDate: '2019-02-24',
      precedentCount: 2,
      precedentDescription: 'Reversion to Japan 1972; ongoing base debates',
      cyclicalRisk: 'Typhoon season (May-Nov)',
    },
    whyItMatters: 'Critical US force projection; Taiwan contingency hub; Korea/China deterrence; first island chain defense',
  },
  {
    id: 'northern_territories',
    name: 'Northern Territories',
    subtext: 'Russia Dispute',
    lat: 44.5,
    lon: 146.5,
    location: 'Kuril Islands (disputed)',
    keywords: ['northern territories', 'kuril islands', 'kunashir', 'iturup', 'shikotan', 'habomai', 'russia japan', 'territorial dispute', 'etorofu', 'hokkaido'],
    agencies: ['MOFA Japan', 'Russian MoD', 'FSB'],
    description: 'Disputed islands between Japan and Russia. Unresolved territorial issue since WWII.',
    status: 'Monitoring',
    escalationScore: 2,
    escalationTrend: 'stable',
    escalationIndicators: ['No peace treaty since 1945', 'Russian military presence', 'Periodic incursions'],
    history: {
      lastMajorEvent: 'Soviet occupation',
      lastMajorEventDate: '1945-09-02',
      precedentCount: 1,
      precedentDescription: 'Occupied by USSR at end of WWII; no resolution in 80 years',
      cyclicalRisk: 'Military exercises periodically',
    },
    whyItMatters: 'Symbol of unresolved WWII disputes; blocks Japan-Russia peace treaty; affects regional security alignment',
  },
  {
    id: 'senkaku',
    name: 'Senkaku Islands',
    subtext: 'China Dispute',
    lat: 25.7439,
    lon: 123.4783,
    location: 'East China Sea (disputed)',
    keywords: ['senkaku', 'diaoyu', 'pinnacle islands', 'east china sea', 'china japan', 'coast guard', 'territorial waters', 'air defense zone', 'incursion'],
    agencies: ['JCG', 'CCG', 'JSDF', 'PLAN'],
    description: 'Disputed islands in East China Sea. Frequent Chinese incursions, Japan Coast Guard patrols.',
    status: 'Monitoring',
    escalationScore: 3,
    escalationTrend: 'escalating',
    escalationIndicators: ['Weekly Chinese incursions', 'JCG confrontations', 'Military aviation nearby'],
    history: {
      lastMajorEvent: 'Nationalization crisis',
      lastMajorEventDate: '2012-09-11',
      precedentCount: 3,
      precedentDescription: '2010 fishing boat collision; 2012 nationalization; ongoing incursions',
      cyclicalRisk: 'Anniversary-related tensions',
    },
    whyItMatters: 'Potential military flashpoint; US-Japan treaty implications; EEZ and resource claims; China assertiveness test',
  },
  {
    id: 'taiwan_strait',
    name: 'Taiwan Strait',
    subtext: 'Regional Flashpoint',
    lat: 24.0,
    lon: 120.0,
    location: 'Taiwan Strait',
    keywords: ['taiwan', 'taiwan strait', 'china taiwan', 'pla', 'tsai', 'lai', 'dpp', 'strait crisis', 'cross strait', 'taipei', 'taiex', 'tsmc'],
    agencies: ['PLAN', 'ROCAF', 'JSDF', 'USFJ'],
    description: 'High-tension area. Taiwan independence debate, Chinese military pressure, Japan security concern.',
    status: 'Monitoring',
    escalationScore: 4,
    escalationTrend: 'escalating',
    escalationIndicators: ['PLA exercises frequent', 'Japan defense white paper concern', 'US-Japan contingency planning'],
    history: {
      lastMajorEvent: 'Pelosi visit crisis',
      lastMajorEventDate: '2022-08-02',
      precedentCount: 4,
      precedentDescription: 'Multiple Taiwan Strait crises (1954-55, 1958, 1995-96, 2022)',
      cyclicalRisk: 'Election cycles heighten tensions',
    },
    whyItMatters: "Critical to Japan's security; major shipping lane; US-China flashpoint; semiconductor supply chain; first island chain integrity",
  },
  {
    id: 'north_korea',
    name: 'Pyongyang',
    subtext: 'Nuclear Threat',
    lat: 39.0392,
    lon: 125.7625,
    location: 'North Korea',
    keywords: ['north korea', 'pyongyang', 'kim jong', 'dprk', 'nuclear test', 'missile launch', 'icbm', 'ballistic missile', 'japan threat', 'korea japan'],
    agencies: ['KPA', 'JSDF', 'USFJ', 'ROK'],
    description: 'Nuclear-armed state. Regular missile tests over/near Japan. Abduction issue unresolved.',
    status: 'Monitoring',
    escalationScore: 3,
    escalationTrend: 'escalating',
    escalationIndicators: ['Frequent missile tests', 'Nuclear threat to Japan', 'Abductee issue', 'Russia-DPRK ties'],
    history: {
      lastMajorEvent: 'Nuclear ICBM tests',
      lastMajorEventDate: '2017-11-29',
      precedentCount: 5,
      precedentDescription: 'Multiple nuclear tests; missile overflights of Japan; abductions',
      cyclicalRisk: 'Provocations during US-ROK exercises',
    },
    whyItMatters: 'Direct nuclear threat to Japan; missile tests trigger J-Alert; abduction issue ongoing; regional stability threat',
  },
  {
    id: 'fukushima',
    name: 'Fukushima',
    subtext: 'Nuclear/Disaster',
    lat: 37.4201,
    lon: 140.4688,
    location: 'Fukushima Prefecture, Japan',
    keywords: ['fukushima', 'nuclear disaster', '311', 'tsunami', 'tepco', 'daiichi', 'reactor', 'decommission', 'treated water', 'alps'],
    agencies: ['TEPCO', 'NRA', 'Japanese Government'],
    description: 'Site of 2011 nuclear disaster. Ongoing decommissioning. Symbol of nuclear safety debate.',
    status: 'Monitoring',
    escalationScore: 2,
    escalationTrend: 'stable',
    escalationIndicators: ['Decommissioning in progress', 'Treated water release', 'Regional concerns'],
    history: {
      lastMajorEvent: 'Great East Japan Earthquake',
      lastMajorEventDate: '2011-03-11',
      precedentCount: 1,
      precedentDescription: 'Level 7 nuclear accident; evacuation zone; 40-year decommissioning',
      cyclicalRisk: 'Earthquake/tsunami vulnerability',
    },
    whyItMatters: 'Nuclear safety concerns; energy policy impact; regional relations (China/Korea water concerns); disaster preparedness',
  },
  {
    id: 'yokosuka',
    name: 'Yokosuka',
    subtext: 'US Naval Base',
    lat: 35.2933,
    lon: 139.6686,
    location: 'Kanagawa Prefecture, Japan',
    keywords: ['yokosuka', 'us navy', 'seventh fleet', 'carrier strike group', 'cfay', 'ship forward deployed', 'ronald reagan', 'naval base japan'],
    agencies: ['US 7th Fleet', 'JMSDF', 'CTF-70'],
    description: 'US Navy forward-deployed naval forces in Western Pacific. Home of 7th Fleet carrier strike group.',
    status: 'Monitoring',
    escalationScore: 1,
    escalationTrend: 'stable',
    escalationIndicators: ['Active carrier operations', 'Regional deterrence posture', 'JMSDF cooperation'],
    history: {
      lastMajorEvent: 'Forward deployment since 1945',
      lastMajorEventDate: '1945-08-30',
      precedentCount: 0,
      precedentDescription: 'Continuous US Navy presence for 80 years',
      cyclicalRisk: 'Operational tempo varies with regional tensions',
    },
    whyItMatters: 'US power projection hub; 7th Fleet HQ; carrier presence; Taiwan/Korea contingency readiness; regional stability',
  },
  {
    id: 'south_korea',
    name: 'Seoul',
    subtext: 'Regional Ally',
    lat: 37.5665,
    lon: 126.9780,
    location: 'South Korea',
    keywords: ['south korea', 'korea', 'seoul', 'rok', 'president yoon', 'samsung', 'hyundai', 'k-pop', 'korea japan', 'gsomia', 'comfort women'],
    agencies: ['ROK Government', 'ROK MOD', 'Blue House'],
    description: 'Key regional ally and economic partner. Complex historical issues. Security cooperation increasing.',
    status: 'Monitoring',
    escalationScore: 2,
    escalationTrend: 'de-escalating',
    escalationIndicators: ['GSOMIA restored', 'Historical tensions easing', 'Security trilateral (US-JP-ROK)'],
    history: {
      lastMajorEvent: 'Yoon administration',
      lastMajorEventDate: '2022-05-10',
      precedentCount: 2,
      precedentDescription: 'Colonial period tensions; comfort women issue; GSOMIA disputes',
      cyclicalRisk: 'Historical anniversaries trigger tensions',
    },
    whyItMatters: 'Second-largest trade partner; GSOMIA intelligence sharing; joint DPRK response; regional security cooperation',
  },
  {
    id: 'beijing',
    name: 'Beijing',
    subtext: 'Regional Power',
    lat: 39.9042,
    lon: 116.4074,
    location: 'China',
    keywords: ['china', 'beijing', 'xi jinping', 'ccp', 'pla', 'chinese', 'sino', 'prc', 'politburo', 'taiwan china', 'south china sea'],
    agencies: ['CCP', 'PLA', 'MSS', 'CMC'],
    description: 'Regional superpower. Complex relationship with Japan. Economic interdependence with security tensions.',
    status: 'Monitoring',
    escalationScore: 3,
    escalationTrend: 'escalating',
    escalationIndicators: ['Senkaku incursions', 'Military modernization', 'Economic coercion concerns'],
    history: {
      lastMajorEvent: 'Xi third term',
      lastMajorEventDate: '2022-10-23',
      precedentCount: 3,
      precedentDescription: 'Wartime occupation; normalization 1972; 2012 Senkaku crisis',
      cyclicalRisk: 'WWII anniversaries heighten tensions',
    },
    whyItMatters: 'Largest trade partner; regional security challenge; Senkaku/Taiwan concerns; economic interdependence vs security rivalry',
  },
];

export const STRATEGIC_WATERWAYS: StrategicWaterway[] = [
  { id: 'taiwan_strait', name: 'TAIWAN STRAIT', lat: 24.0, lon: 119.5, description: 'Critical to Japan security, major shipping lane, PLA activity' },
  { id: 'malacca_strait', name: 'MALACCA STRAIT', lat: 2.5, lon: 101.5, description: 'Major oil/trade route to Japan' },
  { id: 'soya_strait', name: 'SOYA STRAIT', lat: 45.5, lon: 142.0, description: 'Japan-Russia passage, Hokkaido strategic point' },
  { id: 'tsugaru_strait', name: 'TSUGARU STRAIT', lat: 41.5, lon: 140.5, description: 'Between Honshu-Hokkaido, strategic passage' },
  { id: 'tsushima_strait', name: 'TSUSHIMA STRAIT', lat: 34.5, lon: 129.5, description: 'Japan-Korea passage, trade route' },
  { id: 'luzon_strait', name: 'LUZON STRAIT', lat: 20.5, lon: 121.5, description: 'First island chain, Japan sea lane security' },
];

export const APT_GROUPS: APTGroup[] = [
  { id: 'lazarus', name: 'Lazarus', aka: 'Hidden Cobra', sponsor: 'North Korea (RGB)', lat: 38.5, lon: 127.0 },
  { id: 'apt41', name: 'APT41', aka: 'Double Dragon', sponsor: 'China (MSS)', lat: 38.0, lon: 118.0 },
  { id: 'apt28', name: 'APT28/29', aka: 'Fancy Bear/Cozy Bear', sponsor: 'Russia (GRU/FSB)', lat: 55.0, lon: 40.0 },
];

export const CONFLICT_ZONES: ConflictZone[] = [
  {
    id: 'taiwan_strait_tension',
    name: 'Taiwan Strait Tensions',
    coords: [[119, 22], [121, 22], [121, 26], [119, 26]],
    center: [120, 24],
    intensity: 'high',
    parties: ['PRC (PLA)', 'ROC (Taiwan)', 'US (support)', 'Japan (concerned)'],
    casualties: 'No active combat',
    displaced: 'N/A',
    keywords: ['taiwan', 'strait', 'pla', 'exercises', 'strait crisis', 'tsmc'],
    startDate: 'Ongoing since 1949',
    location: 'Taiwan Strait',
    description: 'Persistent military tensions. Regular PLA exercises, air incursions, and naval patrols. US-Japan contingency planning active. Critical to Japan security.',
    keyDevelopments: ['Frequent ADIZ incursions', 'Joint US-Japan exercises', 'Japanese defense posture', 'Semiconductor concerns'],
  },
  {
    id: 'senkaku_dispute',
    name: 'Senkaku/Diaoyu Dispute',
    coords: [[123, 25.3], [123.8, 25.3], [123.8, 26], [123, 26]],
    center: [123.5, 25.7],
    intensity: 'medium',
    parties: ['Japan (JCG)', 'China (CCG)', 'Taiwan (claim)'],
    casualties: 'No casualties (confrontations only)',
    displaced: 'N/A',
    keywords: ['senkaku', 'diaoyu', 'east china sea', 'coast guard', 'territorial'],
    startDate: '1970s-present',
    location: 'Senkaku Islands, East China Sea',
    description: 'Ongoing territorial dispute. Weekly Chinese coast guard incursions into territorial waters. JCG confrontations. Risk of escalation.',
    keyDevelopments: ['CCG law enforcement patrols', 'JCG responses', 'Fishing boat incidents', 'US-Japan treaty coverage'],
  },
  {
    id: 'korean_peninsula',
    name: 'Korean Peninsula Tensions',
    coords: [[126, 37], [129, 37], [129, 39], [126, 39]],
    center: [127.5, 38],
    intensity: 'medium',
    parties: ['DPRK', 'ROK', 'US Forces Korea', 'Japan (regional)'],
    casualties: 'DMZ incidents',
    displaced: 'N/A',
    keywords: ['north korea', 'south korea', 'missile', 'nuclear', 'dmz', 'kim jong un'],
    startDate: 'Armistice 1953',
    location: 'Korean Peninsula DMZ',
    description: 'Frozen conflict since 1953. Frequent DPRK missile tests over/near Japan. Nuclear threat. Japan hosts US forces for Korea contingency.',
    keyDevelopments: ['DPRK missile tests', 'J-Alert activations', 'US-ROK-Japan cooperation', 'Russia-DPRK ties'],
  },
  {
    id: 'south_china_sea',
    name: 'South China Sea',
    coords: [[105, 4], [120, 4], [120, 22], [105, 22]],
    center: [112.5, 13],
    intensity: 'medium',
    parties: ['China', 'Philippines', 'Vietnam', 'Malaysia', 'Taiwan'],
    casualties: 'No active combat',
    displaced: 'N/A',
    keywords: ['south china sea', 'spratly', 'paracel', 'scarborough', 'nine dash'],
    startDate: '1970s-present',
    location: 'South China Sea',
    description: 'Multilateral territorial disputes. Chinese island-building and militarization. ASEAN claimant tensions. Affects Japan sea lanes and regional stability.',
    keyDevelopments: ['Chinese military bases', 'FONOPS', 'Philippine resupply missions', 'Japan regional concern'],
  },
  {
    id: 'northern_territories',
    name: 'Northern Territories Dispute',
    coords: [[145, 43.5], [147.5, 43.5], [147.5, 45.5], [145, 45.5]],
    center: [146.25, 44.5],
    intensity: 'low',
    parties: ['Russia (occupier)', 'Japan (claimant)'],
    casualties: 'N/A',
    displaced: 'N/A',
    keywords: ['northern territories', 'kuril', 'russia japan', 'territorial dispute'],
    startDate: 'Since 1945',
    location: 'Southern Kuril Islands',
    description: 'Unresolved WWII territorial dispute. Four islands occupied by Russia, claimed by Japan. No peace treaty signed. Periodic Russian military exercises.',
    keyDevelopments: ['Russian military presence', 'Diplomatic impasse', 'Resource development', 'Ukraine war impact'],
  },
  {
    id: 'ukraine_russia',
    name: 'Ukraine Conflict (Regional Impact)',
    coords: [[30, 48], [38, 48], [38, 51], [30, 51]],
    center: [34, 49.5],
    intensity: 'high',
    parties: ['Russia', 'Ukraine', 'NATO support'],
    casualties: '500,000+ (est.)',
    displaced: '6.5M+ refugees',
    keywords: ['ukraine', 'russia', 'sanctions', 'energy'],
    startDate: 'Feb 24, 2022',
    location: 'Ukraine',
    description: 'Ongoing war affecting Japan through sanctions coordination (G7), energy markets, Russia-Japan relations, and regional security implications.',
    keyDevelopments: ['Japan sanctions', 'G7 coordination', 'Russia-Japan relations frozen', 'Energy security'],
  },
];


// Japan-relevant undersea cables
export const UNDERSEA_CABLES: UnderseaCable[] = [
  {
    id: 'faster',
    name: 'FASTER',
    points: [[-122.0, 37.0], [-155.0, 22.0], [139.0, 35.0]],
    major: true,
    capacityTbps: 60,
    rfsYear: 2016,
    owners: ['Google', 'China Mobile', 'China Telecom', 'KDDI', 'SingTel'],
    landingPoints: [
      { country: 'US', countryName: 'United States', city: 'Oregon', lat: 43.37, lon: -124.22 },
      { country: 'JP', countryName: 'Japan', city: 'Chikura', lat: 34.95, lon: 139.95 },
      { country: 'JP', countryName: 'Japan', city: 'Shima', lat: 34.32, lon: 136.85 },
    ],
    countriesServed: [
      { country: 'US', capacityShare: 0.03, isRedundant: true },
      { country: 'JP', capacityShare: 0.15, isRedundant: true },
    ],
  },
  {
    id: 'jupiter',
    name: 'Jupiter',
    points: [[-122.0, 37.0], [139.0, 35.0]],
    major: true,
    capacityTbps: 144,
    rfsYear: 2024,
    owners: ['Google', 'KDDI'],
    landingPoints: [
      { country: 'US', countryName: 'United States', city: 'California', lat: 37.0, lon: -122.0 },
      { country: 'JP', countryName: 'Japan', city: 'Chikura', lat: 34.95, lon: 139.95 },
    ],
    countriesServed: [
      { country: 'US', capacityShare: 0.05, isRedundant: true },
      { country: 'JP', capacityShare: 0.20, isRedundant: true },
    ],
  },
];

// Japan-relevant military bases (from MILITARY_BASES_EXPANDED or create minimal list)
export const MILITARY_BASES: MilitaryBase[] = MILITARY_BASES_EXPANDED.filter(base => 
  base.country === 'Japan' || (base.lat > 24 && base.lat < 46 && base.lon > 122 && base.lon < 154)
);

// Japan-relevant nuclear facilities
export const NUCLEAR_FACILITIES: NuclearFacility[] = [
  { id: 'fukushima', name: 'Fukushima Daiichi', lat: 37.4217, lon: 140.4730, type: 'plant', operator: 'TEPCO (Japan)', status: 'decommissioned' },
  { id: 'kashiwazaki', name: 'Kashiwazaki-Kariwa', lat: 37.4260, lon: 138.5946, type: 'plant', operator: 'TEPCO (Japan)', status: 'inactive' },
  { id: 'takahama', name: 'Takahama', lat: 35.5236, lon: 135.5034, type: 'plant', operator: 'Kansai Electric (Japan)', status: 'active' },
  { id: 'ohi', name: 'Ohi', lat: 35.5422, lon: 135.6517, type: 'plant', operator: 'Kansai Electric (Japan)', status: 'active' },
  { id: 'genkai', name: 'Genkai', lat: 33.5156, lon: 129.8350, type: 'plant', operator: 'Kyushu Electric (Japan)', status: 'active' },
];

export const MAP_URLS = {
  overviewMap: 'https://example.com/map.json',
  world: '/data/countries.geojson',
};

export const SANCTIONED_COUNTRIES: string[] = ['KP', 'RU'];





export const ECONOMIC_CENTERS: EconomicCenter[] = [
  // Americas
  { id: 'nyse', name: 'NYSE', type: 'exchange', lat: 40.7069, lon: -74.0089, country: 'USA', marketHours: { open: '09:30', close: '16:00', timezone: 'America/New_York' }, description: 'New York Stock Exchange - World\'s largest stock exchange' },
  { id: 'nasdaq', name: 'NASDAQ', type: 'exchange', lat: 40.7569, lon: -73.9896, country: 'USA', marketHours: { open: '09:30', close: '16:00', timezone: 'America/New_York' }, description: 'Tech-heavy exchange' },
  { id: 'fed', name: 'Federal Reserve', type: 'central-bank', lat: 38.8927, lon: -77.0459, country: 'USA', description: 'US Central Bank - Controls USD monetary policy' },
  { id: 'cme', name: 'CME Group', type: 'exchange', lat: 41.8819, lon: -87.6278, country: 'USA', description: 'Chicago Mercantile Exchange - Futures & derivatives' },
  { id: 'tsx', name: 'TSX', type: 'exchange', lat: 43.6489, lon: -79.3850, country: 'Canada', marketHours: { open: '09:30', close: '16:00', timezone: 'America/Toronto' }, description: 'Toronto Stock Exchange' },
  { id: 'bovespa', name: 'B3', type: 'exchange', lat: -23.5505, lon: -46.6333, country: 'Brazil', description: 'Brazilian Stock Exchange (B3/Bovespa)' },
  // Europe
  { id: 'lse', name: 'LSE', type: 'exchange', lat: 51.5145, lon: -0.0940, country: 'UK', marketHours: { open: '08:00', close: '16:30', timezone: 'Europe/London' }, description: 'London Stock Exchange' },
  { id: 'boe', name: 'Bank of England', type: 'central-bank', lat: 51.5142, lon: -0.0880, country: 'UK', description: 'UK Central Bank' },
  { id: 'ecb', name: 'ECB', type: 'central-bank', lat: 50.1096, lon: 8.6732, country: 'Germany', description: 'European Central Bank - Controls EUR' },
  { id: 'euronext', name: 'Euronext', type: 'exchange', lat: 48.8690, lon: 2.3364, country: 'France', marketHours: { open: '09:00', close: '17:30', timezone: 'Europe/Paris' }, description: 'Pan-European Exchange (Paris, Amsterdam, Brussels, Lisbon)' },
  { id: 'dax', name: 'Deutsche Börse', type: 'exchange', lat: 50.1109, lon: 8.6821, country: 'Germany', marketHours: { open: '09:00', close: '17:30', timezone: 'Europe/Berlin' }, description: 'Frankfurt Stock Exchange - DAX' },
  { id: 'six', name: 'SIX Swiss', type: 'exchange', lat: 47.3769, lon: 8.5417, country: 'Switzerland', description: 'Swiss Exchange' },
  { id: 'snb', name: 'SNB', type: 'central-bank', lat: 46.9480, lon: 7.4474, country: 'Switzerland', description: 'Swiss National Bank' },
  // Asia-Pacific
  { id: 'tse', name: 'Tokyo SE', type: 'exchange', lat: 35.6830, lon: 139.7744, country: 'Japan', marketHours: { open: '09:00', close: '15:00', timezone: 'Asia/Tokyo' }, description: 'Tokyo Stock Exchange - Nikkei' },
  { id: 'boj', name: 'Bank of Japan', type: 'central-bank', lat: 35.6855, lon: 139.7579, country: 'Japan', description: 'Japan Central Bank - Controls JPY' },
  { id: 'sse', name: 'Shanghai SE', type: 'exchange', lat: 31.2304, lon: 121.4737, country: 'China', marketHours: { open: '09:30', close: '15:00', timezone: 'Asia/Shanghai' }, description: 'Shanghai Stock Exchange' },
  { id: 'szse', name: 'Shenzhen SE', type: 'exchange', lat: 22.5431, lon: 114.0579, country: 'China', description: 'Shenzhen Stock Exchange - Tech focus' },
  { id: 'pboc', name: 'PBOC', type: 'central-bank', lat: 39.9208, lon: 116.4074, country: 'China', description: 'People\'s Bank of China - Controls CNY' },
  { id: 'hkex', name: 'HKEX', type: 'exchange', lat: 22.2833, lon: 114.1577, country: 'Hong Kong', marketHours: { open: '09:30', close: '16:00', timezone: 'Asia/Hong_Kong' }, description: 'Hong Kong Exchange' },
  { id: 'sgx', name: 'SGX', type: 'exchange', lat: 1.2834, lon: 103.8607, country: 'Singapore', description: 'Singapore Exchange' },
  { id: 'mas', name: 'MAS', type: 'central-bank', lat: 1.2789, lon: 103.8536, country: 'Singapore', description: 'Monetary Authority of Singapore' },
  { id: 'kospi', name: 'KRX', type: 'exchange', lat: 37.5665, lon: 126.9780, country: 'South Korea', marketHours: { open: '09:00', close: '15:30', timezone: 'Asia/Seoul' }, description: 'Korea Exchange - KOSPI' },
  { id: 'bse', name: 'BSE', type: 'exchange', lat: 18.9307, lon: 72.8335, country: 'India', marketHours: { open: '09:15', close: '15:30', timezone: 'Asia/Kolkata' }, description: 'Bombay Stock Exchange - Sensex' },
  { id: 'nse', name: 'NSE India', type: 'exchange', lat: 19.0571, lon: 72.8621, country: 'India', description: 'National Stock Exchange - Nifty' },
  { id: 'rbi', name: 'RBI', type: 'central-bank', lat: 18.9322, lon: 72.8351, country: 'India', description: 'Reserve Bank of India' },
  { id: 'asx', name: 'ASX', type: 'exchange', lat: -33.8688, lon: 151.2093, country: 'Australia', marketHours: { open: '10:00', close: '16:00', timezone: 'Australia/Sydney' }, description: 'Australian Securities Exchange' },
  { id: 'rba', name: 'RBA', type: 'central-bank', lat: -33.8654, lon: 151.2105, country: 'Australia', description: 'Reserve Bank of Australia' },
  // Middle East & Africa
  { id: 'tadawul', name: 'Tadawul', type: 'exchange', lat: 24.6877, lon: 46.7219, country: 'Saudi Arabia', marketHours: { open: '10:00', close: '15:00', timezone: 'Asia/Riyadh' }, description: 'Saudi Stock Exchange - Largest in Arab world' },
  { id: 'adx', name: 'ADX', type: 'exchange', lat: 24.4539, lon: 54.3773, country: 'UAE', marketHours: { open: '10:00', close: '14:00', timezone: 'Asia/Dubai' }, description: 'Abu Dhabi Securities Exchange' },
  { id: 'dfm', name: 'DFM', type: 'exchange', lat: 25.2221, lon: 55.2867, country: 'UAE', marketHours: { open: '10:00', close: '14:00', timezone: 'Asia/Dubai' }, description: 'Dubai Financial Market' },
  { id: 'qse', name: 'QSE', type: 'exchange', lat: 25.2854, lon: 51.5310, country: 'Qatar', marketHours: { open: '09:30', close: '13:15', timezone: 'Asia/Qatar' }, description: 'Qatar Stock Exchange' },
  { id: 'bkw', name: 'Boursa Kuwait', type: 'exchange', lat: 29.3759, lon: 47.9774, country: 'Kuwait', marketHours: { open: '09:00', close: '12:30', timezone: 'Asia/Kuwait' }, description: 'Kuwait Stock Exchange' },
  { id: 'bse_bahrain', name: 'Bahrain Bourse', type: 'exchange', lat: 26.2285, lon: 50.5860, country: 'Bahrain', description: 'Bahrain Stock Exchange' },
  { id: 'egx', name: 'EGX', type: 'exchange', lat: 30.0444, lon: 31.2357, country: 'Egypt', marketHours: { open: '10:00', close: '14:30', timezone: 'Africa/Cairo' }, description: 'Egyptian Exchange - Cairo' },
  { id: 'tase', name: 'TASE', type: 'exchange', lat: 32.0853, lon: 34.7818, country: 'Israel', marketHours: { open: '09:59', close: '17:14', timezone: 'Asia/Jerusalem' }, description: 'Tel Aviv Stock Exchange' },
  { id: 'jse', name: 'JSE', type: 'exchange', lat: -26.1447, lon: 28.0381, country: 'South Africa', marketHours: { open: '09:00', close: '17:00', timezone: 'Africa/Johannesburg' }, description: 'Johannesburg Stock Exchange' },
  { id: 'nse_nigeria', name: 'NGX', type: 'exchange', lat: 6.4541, lon: 3.4218, country: 'Nigeria', description: 'Nigerian Exchange Group - Lagos' },
  { id: 'casa', name: 'Casablanca SE', type: 'exchange', lat: 33.5731, lon: -7.5898, country: 'Morocco', description: 'Casablanca Stock Exchange' },
  // Financial Hubs (not exchanges but major centers)
  { id: 'dubai_hub', name: 'DIFC', type: 'financial-hub', lat: 25.2116, lon: 55.2708, country: 'UAE', description: 'Dubai International Financial Centre' },
  { id: 'cayman', name: 'Cayman Islands', type: 'financial-hub', lat: 19.3133, lon: -81.2546, country: 'Cayman Islands', description: 'Offshore financial center' },
  { id: 'luxembourg', name: 'Luxembourg', type: 'financial-hub', lat: 49.6116, lon: 6.1319, country: 'Luxembourg', description: 'European investment fund center' },
];

export const SPACEPORTS: Spaceport[] = [
  { id: 'ksc', name: 'Kennedy Space Center', lat: 28.57, lon: -80.64, country: 'USA', operator: 'NASA/Space Force', status: 'active', launches: 'High' },
  { id: 'vandenberg', name: 'Vandenberg SFB', lat: 34.74, lon: -120.57, country: 'USA', operator: 'US Space Force', status: 'active', launches: 'Medium' },
  { id: 'boca_chica', name: 'Starbase', lat: 25.99, lon: -97.15, country: 'USA', operator: 'SpaceX', status: 'active', launches: 'High' },
  { id: 'baikonur', name: 'Baikonur Cosmodrome', lat: 45.96, lon: 63.30, country: 'Kazakhstan', operator: 'Roscosmos', status: 'active', launches: 'Medium' },
  { id: 'plesetsk', name: 'Plesetsk Cosmodrome', lat: 62.92, lon: 40.57, country: 'Russia', operator: 'Roscosmos/Military', status: 'active', launches: 'Medium' },
  { id: 'vostochny', name: 'Vostochny Cosmodrome', lat: 51.88, lon: 128.33, country: 'Russia', operator: 'Roscosmos', status: 'active', launches: 'Low' },
  { id: 'jiuquan', name: 'Jiuquan SLC', lat: 40.96, lon: 100.29, country: 'China', operator: 'CNSA', status: 'active', launches: 'High' },
  { id: 'xichang', name: 'Xichang SLC', lat: 28.24, lon: 102.02, country: 'China', operator: 'CNSA', status: 'active', launches: 'High' },
  { id: 'wenchang', name: 'Wenchang SLC', lat: 19.61, lon: 110.95, country: 'China', operator: 'CNSA', status: 'active', launches: 'Medium' },
  { id: 'kourou', name: 'Guiana Space Centre', lat: 5.23, lon: -52.76, country: 'France', operator: 'ESA/CNES', status: 'active', launches: 'Medium' },
  { id: 'sriharikota', name: 'Satish Dhawan SC', lat: 13.72, lon: 80.23, country: 'India', operator: 'ISRO', status: 'active', launches: 'Medium' },
  { id: 'tanegashima', name: 'Tanegashima SC', lat: 30.40, lon: 130.97, country: 'Japan', operator: 'JAXA', status: 'active', launches: 'Low' },
];

export const CRITICAL_MINERALS: CriticalMineralProject[] = [
  // Lithium
  { id: 'greenbushes', name: 'Greenbushes', lat: -33.86, lon: 116.01, mineral: 'Lithium', country: 'Australia', operator: 'Talison Lithium', status: 'producing', significance: 'Largest hard-rock lithium mine' },
  { id: 'atacama', name: 'Salar de Atacama', lat: -23.50, lon: -68.33, mineral: 'Lithium', country: 'Chile', operator: 'SQM/Albemarle', status: 'producing', significance: 'Largest brine lithium source' },
  { id: 'pilgangoora', name: 'Pilgangoora', lat: -21.03, lon: 118.91, mineral: 'Lithium', country: 'Australia', operator: 'Pilbara Minerals', status: 'producing', significance: 'Major hard-rock deposit' },
  { id: 'silver_peak', name: 'Silver Peak', lat: 37.75, lon: -117.65, country: 'USA', mineral: 'Lithium', operator: 'Albemarle', status: 'producing', significance: 'Only active US lithium mine' },
  // Cobalt
  { id: 'mutanda', name: 'Mutanda', lat: -10.78, lon: 25.80, mineral: 'Cobalt', country: 'DRC', operator: 'Glencore', status: 'producing', significance: 'World largest cobalt mine' },
  { id: 'tenke', name: 'Tenke Fungurume', lat: -10.61, lon: 26.16, mineral: 'Cobalt', country: 'DRC', operator: 'CMOC', status: 'producing', significance: 'Major Chinese-owned cobalt source' },
  // Rare Earths
  { id: 'bayan_obo', name: 'Bayan Obo', lat: 41.76, lon: 109.95, mineral: 'Rare Earths', country: 'China', operator: 'China Northern Rare Earth', status: 'producing', significance: 'World largest REE mine (45% global production)' },
  { id: 'mountain_pass', name: 'Mountain Pass', lat: 35.47, lon: -115.53, mineral: 'Rare Earths', country: 'USA', operator: 'MP Materials', status: 'producing', significance: 'Only major US REE mine' },
  { id: 'mount_weld', name: 'Mount Weld', lat: -28.86, lon: 122.17, mineral: 'Rare Earths', country: 'Australia', operator: 'Lynas', status: 'producing', significance: 'Major non-Chinese REE source' },
  // Nickel
  { id: 'wedabay', name: 'Weda Bay', lat: 0.47, lon: 127.94, mineral: 'Nickel', country: 'Indonesia', operator: 'Tsingshan/Eramet', status: 'producing', significance: 'Massive nickel pig iron production' },
  { id: 'norilsk', name: 'Norilsk', lat: 69.33, lon: 88.21, mineral: 'Nickel', country: 'Russia', operator: 'Nornickel', status: 'producing', significance: 'Major palladium/nickel source' },
];
